### ISSUE TITLE
CSV upload fails

### ISSUE THREAD

**Issue by olivierobert** [mohd497/nimble3_test#1]
![nimbl3test_and_https___www_tripadvisor_com_pricefinderpopunder_and_your_booking_confirmation_-_olivierobert_gmail_com_-_gmail](https://cloud.githubusercontent.com/assets/696529/20048809/c1358212-a4f1-11e6-87b8-ae84cc61ede0.png)

Content of the file:

![keywords_csv_ __users_olivier_google_drive_3__operations_2__hr_recruitment_code_assignment_templates](https://cloud.githubusercontent.com/assets/696529/20048855/04152b14-a4f2-11e6-906f-3c403fe4efe8.png)

**Comment by mohd497** [comment]
hi Olivier,

Sorry for late reply. I was out. I have tested it on my end. It was working
fine. Maybe the syntax of csv it can't recognize.
I am giving you my test csv.
